name: compras
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  go_router: ^15.2.4
  provider: ^6.1.5
  path: ^1.9.1
  sqflite: ^2.4.2
  uuid: ^4.5.1
  google_fonts: ^6.2.1
  material_symbols_icons: ^4.2815.1
  intl: ^0.20.2
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.5.4
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  sqflite_common_ffi: ^2.3.6


flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  #
  
  
