pdf:
	pandoc \
		-o compras.pdf \
		--from=markdown \
		--pdf-engine=xelatex \
		--highlight-style=tango \
		-V lang=pt \
		index.md \
		introduction.md \
		Architecture.md \
		Changelog.md \
		ai_ready.md

